
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Makefile", "Makefile\Makefile.vcxproj", "{8463D0FA-0382-4CF4-A385-21CEA04B5C20}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Win32 = Debug|Win32
		Release|Win32 = Release|Win32
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8463D0FA-0382-4CF4-A385-21CEA04B5C20}.Debug|Win32.ActiveCfg = Debug|Win32
		{8463D0FA-0382-4CF4-A385-21CEA04B5C20}.Debug|Win32.Build.0 = Debug|Win32
		{8463D0FA-0382-4CF4-A385-21CEA04B5C20}.Release|Win32.ActiveCfg = Release|Win32
		{8463D0FA-0382-4CF4-A385-21CEA04B5C20}.Release|Win32.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
